### ISSUE TITLE
[CG] Update

### ISSUE THREAD

**Issue by sasadj1** [wssto2/rv-nissan-header-footer-cg-bih-mk-main#1]
Grga,
trebalo bi updateati h/f na RV/NV stranicama za Crnu goru:
- https://www.upotrebljavanavozila.nissan.me/
- https://www.izaberiiodvezi.nissan.me/

Vidi hoće li Fran to rješavati...

Tnx,
Saša

**Comment by gborac** [comment]
riješeno
